---
driver:
  name: docker
  docker: /usr/bin/docker
  use_sudo: false
  provision_command: curl -L http://www.opscode.com/chef/install.sh | bash

provisioner::
  require_chef_omnibus: 12.3.0


platforms:
- name: centos-6.6
  driver_config:
    image: centos:6.6
    platform: centos

suites:
  - name: default
    run_list:
    - recipe[template::default]
    attributes:
